### PR TITLE
Youtube fix

### PR DESCRIPTION
**Pull request by Nikhilatvocabustudy**
Added that youtube was a page, as well as more info

### CODE REVIEW

**Comment by Nikhilatvocabustudy** [comment]
Same error happened, let me fix

**Comment by grimsteel** [comment]
Duplicate of #252 

Just add a link to "/#youtube" somewhere like in the Discord page, the footer, or the navbar (pick one)

**Comment by Nikhilatvocabustudy** [comment]
> 

not to sure as to what you mean by this

**Comment by grimsteel** [comment]
This pull request is basically the same as #252. #252 is almost ready to merge, but as of now, it's impossible to access the Youtube page you created except if you know the link. I would recommend adding it to the footer

**Comment by Nikhilatvocabustudy** [comment]
ah got you

**Pull request closed without merging**
